### ISSUE TITLE
Error on Windows Cygwin

### ISSUE THREAD

**Issue by andremrezende** [Skullabs/kikaha#143]
After ran:
curl -s http://skullabs.github.io/kikaha-cli/installer | bash
kikaha setup
And convert  plugin.project.sh to DOS using dos2unix.exe
When I ran the follow command:kikaha project create empty-project --artifact_id=first-project
Throws:
 16:44:41.488 [main] DEBUG o.a.m.a.c.DefaultArchetypeArtifactManager - Archetype io.skullabs.kikaha.archetypes:empty-project-archetype:1.0.0 doesn't exist
org.apache.maven.archetype.downloader.DownloadNotFoundException: Requested io.skullabs.kikaha.archetypes:empty-project-archetype:jar:1.0.0 download does not exist.
        at org.apache.maven.archetype.downloader.DefaultDownloader.download(DefaultDownloader.java:78) ~[archetype-common-2.4.jar:2.4]
        at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.exists(DefaultArchetypeArtifactManager.java:278) ~[archetype-common-2.4.jar:2.4]
        at org.apache.maven.archetype.ui.generation.DefaultArchetypeGenerationConfigurator.configureArchetype(DefaultArchetypeGenerationConfigurator.java:116) [maven-archetype-plugin-2.4.jar:2.4]
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:189) [maven-archetype-plugin-2.4.jar:2.4]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) [maven-embedder-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) [maven-embedder-3.3.9.jar:3.3.9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Could not find artifact io.skullabs.kikaha.archetypes:empty-project-archetype:jar:1.0.0 in nexus (http://serv-dbr.posthaus.com.br:8081/nexus/content/groups/public)

Try downloading the file manually from the project website.

Should I do some else?

**Comment by miere** [comment]
Hi @andremrezende I just did a look and it seems to have a bug at the Windows execution environment. Could you, please, attach the output your ```curl -s http://skullabs.github.io/kikaha-cli/installer | bash``` and ```kikaha setup```. I will check if the bug is the same I found and apply a patch to fix this issue.

**Comment by miere** [comment]
@andremrezende it is apparently fixed at the **kikaha-cli** version. The ```2.0.0``` will be closed until June 30, could you please give it another try so I can close this issue?
