### ISSUE TITLE
server.urouting.default-content-type configuration doesn't apply to DefaultResponse.contentType

### ISSUE THREAD

**Issue by jianhuiz** [Skullabs/kikaha#202]
DefaultResponse.contentType always is "text/plain"
Wouldn't it a good idea to read the config "server.urouting.default-content-type"
So does the "server.urouting.default-encoding".

**Comment by miere** [comment]
Hi @jianhuiz this is actually a quite good suggestion.
I'll apply a patch into this and make it available to the next 2.1.0 alpha release. I'll apply the same patch onto the 2.0.x branch too.

**Comment by miere** [comment]
Hi @jianhuiz I just pushed the 2.1.0-alpha7 version to the maven central.
Could you, please, give a try on this version and see if the current version have fixed this issue to you?
Once you give me a positive feedback about this issue, I will apply the same patch into the 2.0.x version.

**Comment by jianhuiz** [comment]
Unfortunately it didn't work. I get the serializer error:
```
[ERROR] SerializerAndUnserializerProvider - Could not found a serializer for null
kikaha.urouting.UnsupportedMediaTypeException: null
        at kikaha.urouting.SerializerAndUnserializerProvider.getSerializerFor(SerializerAndUnserializerProvider.java:20) ~[kikaha-urouting-2.1.0-alpha7.jar:na]
        at kikaha.urouting.RoutingMethodResponseWriter.getSerializer(RoutingMethodResponseWriter.java:119) [kikaha-urouting-2.1.0-alpha7.jar:na]
        at kikaha.urouting.RoutingMethodResponseWriter.sendBodyResponse(RoutingMethodResponseWriter.java:113) [kikaha-urouting-2.1.0-alpha7.jar:na]
        at kikaha.urouting.RoutingMethodResponseWriter.write(RoutingMethodResponseWriter.java:101) [kikaha-urouting-2.1.0-alpha7.jar:na]
```

**Comment by miere** [comment]
@jianhuiz thank you for your feedback.

Indeed, my initial tests were based on wrong assertions and it let the NPE being thrown. I was able to reproduce this NPE error locally and I've just applied a patch into the _master_ branch. This night (at timezone -3 :P) I'll publish a new alpha version onto the Maven Central.

**Comment by miere** [comment]
@jianhuiz I just pushed the 2.1.0-alpha8 version onto the Maven Central. ;)

**Comment by jianhuiz** [comment]
the new version breaks back compatibility and behaves strangely.

before this version when I write
`return DefaultResponse.ok(entity).header(Headers.CONTENT_TYPE_STRING, Mimes.JSON);` 
I manually encode entity to a json string, kikaha doesn't do it for me.

in this version, kikaha encode the entity object to json all the time, no matter what content type I provided.


My initial intention to raise this issue is just want to save the `.header(Headers.CONTENT_TYPE_STRING, Mimes.JSON);`  for every of my responses.

**Comment by miere** [comment]
Hi @jianhuiz 

> My initial intention to raise this issue is just want to save the .header(Headers.CONTENT_TYPE_STRING, Mimes.JSON); for every of my responses.

The first time I read this issue I didn't realize that you were using the `DefaultResponse.header` to define the response Content-Type. The expected, and recommended, approach should be `DefaultResponse.contentType`.

>before this version when I write
return DefaultResponse.ok(entity).header(Headers.CONTENT_TYPE_STRING, Mimes.JSON);
I manually encode entity to a json string, kikaha doesn't do it for me.

This also explains why you had to manually encode your objects into a JSON string, once Kikaha was only looking for Content-Types on `Response.contentType()`.

_I'll ensure that Kikaha will also take a look on the Response.headers() to define which would be the output's Content-Type and automatically serialize it for you - if you opt to use `Response.headers()` instead of `Response.contentType()`. I'll patch it for you this night._ #204

Another approach to solve this would be using the `@kikaha.urouting.api.Produces` annotation to 'manually' define the default Content-Type when you are returning a `kikaha.urouting.api.Response` object. Here is an example:

```java
import java.util.*;
import javax.inject.*;
import kikaha.urouting.api.*;

@Path( "users" )
@Singleton
@Produces( Mimes.JSON )
public class UserResource {

    @lombok.Getter
    final Map<Long, User> users = new HashMap<>();

    @GET
    public Response retrieveAllUsers(){
      return DefaultResponse.ok( users.values() );
    }

    @GET
    @Path( "{id}" )
    public User retrieveUserById(
            @PathParam( "id" ) long id ) {
        return users.get( id );
    }

    @POST
    public void persistUser( User user ) {
        users.put( user.getId(), user );
    }
}

@Data
public class User {

    final long id = System.currentTimeMillis();

    @NonNull
    String name;
}
```
You can also notice that you may return the expected object on the routing methods. Kikaha will infer the 200 status code as response and use the output Content-Type to do the serialization for you.

**Comment by miere** [comment]
Also, this rises me a question: **Wasn't the [documentation](http://get.kikaha.io/docs/urouting-api) clear enough?**
This topic at the documentation was clear enough to helps you to create your routes or was it a lil' fuzzy?
How could I improve it to be clearer?

**Comment by jianhuiz** [comment]
I wasn't aware of the `Response.contentType()` method.
But I did tried add `@Produces(Mimes.JSON)` annotations which seemed only work when returning the api object (User in your example), not when returning DefaultResponse()

**Comment by miere** [comment]
@jianhuiz I just pushed the 2.1.0-alpha9 to the maven central and you can test if this have fixed the #204 issue. I'm sorry for the late delay, I was focused on the #203 regarding Protobuf support - it took more time than I was expecting...

**Comment by miere** [comment]
Hi @jianhuiz 
It has been a while since our last interaction and I would like to hear your feedback about the latest updates on Kikaha, especially this one. We will soon close a final version and I'd appreciate any honest feedback users can provide us.
